d36/d36/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('racer/', include('racer.urls')),
    path('events/', include('races.urls')),
    path('admin/', admin.site.urls),
]

d36/racer/urls.py
from django.urls import path

from . import views

app_name = 'racer'
urlpatterns = [
    path('',views.index, name='index'),
    path('<str:district_num>/', views.racer, name='racer')
  #  path('add_racer/', views.add_racer, name='add_racer')
]

d36/races/urls.py
from django.urls import path

from . import views

app_name = 'races'
urlpatterns = [
    path('',views.index, name='index'),
    path('<str:event_name>/', views.event, name='event'),
    path('<int:year>/<str:race>/', views.race)
]

d36/racer/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Racer(models.Model):
    """A District Racer's Profile"""
    # Contact Info
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.CharField(max_length=25)
    phone = models.CharField(max_length=25)
    address = models.CharField(max_length=40)
    city = models.CharField(max_length=40)
    state = models.CharField(max_length=12)
    zip_code = models.IntegerField()
    
    # District / AMA Info
    ama_num = models.IntegerField()
    district_num = models.CharField(max_length=5)
    date_joined = models.DateTimeField('date joined')
    
    # Social Media Links
    instragram = models.CharField(max_length=20)
    facebook = models.CharField(max_length=50)
    twitter = models.CharField(max_length=20)
    linkedin = models.CharField(max_length=50)
    
    def __str__(self):
    	return ",".join([str(self.ama_num), self.district_num, self.first_name,
    				     self.last_name, self.city, self.state, str(self.date_joined)])

class Sponsors(models.Model):
	"""Sponsors for a given Racer."""
	racer = models.ForeignKey(Racer, on_delete=models.CASCADE)
	sponsor = models.CharField(max_length=25)
	sponsor_img = models.URLField()
	sponsor_url = models.URLField()
	year = models.IntegerField()
	
	def __str__(self):
	    return self.racer.district_num + ":" + self.sponsor
	    
	def is_current(self):
		return self.year >= timezone.now().year

d36/races/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    """A Distinct Event, ie name of a race"""
    # Contact Info
    name = models.CharField(max_length=25)
    promoter = models.CharField(max_length=25)
   # discipline = models.CharField(choices=['Enduro', 'Cross-Country', 'Flat Track'])

    def __str__(self):
        return self.name + self.promoter
       
class Race(models.Model):
    "A Race event"
    event = models.ForeignKey(Event, on_delete='CASCADE')
    start_date = models.DateField()
    end_date = models.DateField()
    year = models.IntegerField(max_length=9999)
    location = models.CharField(max_length=25)
    rescheduled = models.BooleanField()
    points = models.BooleanField()
    flier_url = models.URLField()

    def __str__(self):
        return self.event.name +str(self.start_date)

d36/racer/forms.py
from django import forms

class RacerForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

d36/racer/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader

from .models import Racer, Sponsors

def index(request):
	racers = Racer.objects.order_by('last_name')
	template = loader.get_template('racer/index.html')
	context = {
		'racers': racers
	}
	return render(request, 'racer/index.html', context)
    
def racer(request, district_num):
	"""View to see a racers details."""
	racer = get_object_or_404(Racer, district_num=district_num)
	try:
		sponsors = Sponsors.objects.filter(racer=racer.id)
	except:
		sponsors = None
	return render(request, 'racer/racer.html', {'racer':racer, 'sponsors':sponsors})

d36/races/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Event, Race
# Create your views here.

def index(request):
    return HttpResponse("<h1> Hello </h1>")
    
def event(request, event):
	"""View to see a racers details."""
	return HttpResponse("<h1> Hello event</h1>")

def race(request, year, race):
    """View to see a races details."""
    
    return HttpResponse("<h1> Hello %s %s</h1>" % (race, year))

d36/racer/templates/racer/add_racer.html
<h1> Add Racer Profile </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'racer:add_racer' racer.id %}" method="post">
{% csrf_token %}
   <input id="first_name" type="text" name="first_name" maxlength="100" required>
   <input id="last_name" type="text" name="last_name" maxlength="100" required>
<input type="submit" value="add_racer">
</form>

d36/racer/templates/racer/index.html
{% if racers %}
    <ul>
    {% for racer in racers %}
        <li><a href="{% url 'racer:racer' racer.district_num %}/">{{ racer }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No racers are available.</p>
{% endif %}

d36/racer/templates/racer/racer.html
<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="card">
  <h1>{{ racer.first_name }} {{ racer.last_name }}</h1>
  <p class="title">{{ racer.district_num }}</p>
  <p>{{ racer.city }}</p>
  <a href="https://www.instagram.com/{{ racer.instragram }}/"><i class="fa fa-instagram"></i></a> 
  <a href="#"><i class="fa fa-twitter"></i></a> 
  <a href="#"><i class="fa fa-linkedin"></i></a> 
  <a href="#"><i class="fa fa-facebook"></i></a>
  {% if sponsors %}
  <p class="list">Sponsors</p>
	{% for sponsor in sponsors %}
		<a href="{{ sponsor.sponsor_url }}/">
			<img width="100%" height="5%" src="{{ sponsor.sponsor_img }}">
		</a>
	<br>
	{% endfor %}
	
	{% endif %}
</div>

<style>
.card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    max-width: 700px;
    margin: auto;
    text-align: center;
}

.title {
    color: grey;
    font-size: 18px;
}

.list {
    border: none;
    outline: 0;
    display: inline-block;
    padding-top: 8px;
    padding-bottom: 8px;
    color: white;
    background-color: #000;
    text-align: center;
    cursor: pointer;
    width: 100%;
    font-size: 18px;
}

a {
    text-decoration: none;
    font-size: 22px;
    color: black;
}

button:hover, a:hover {
    opacity: 0.7;
}
</style>